### PR TITLE
implement Leaflet B1 compatibility

### PR DESCRIPTION
**Pull request by snkashis**
Bringing up to date with Leaflet B1.Layer bindings needed changing.

### CODE REVIEW

**Comment by snkashis** [comment]
Maybe we should leave this in a seperate branch until 1.0 stable is released?

**Comment by elesdoar** [comment]
Thanks

Yes, we should separate on another branch.

**Comment by snkashis** [comment]
@elesdoar I think you need to create that branch, then I can target a pull request into it.

**Comment by elesdoar** [comment]
OK, I did create leaflet-1.x brach. Thanks

**Comment by snkashis** [comment]
Okay, new pull at https://github.com/elesdoar/leaflet-control-orderlayers/pull/11

**Pull request closed without merging**
